[window]
opacity = 1.0
decorations = "none"
startup_mode = "Maximized"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 16.0

[font.normal]
family = "DejaVu Sans Mono"
style = "Regular"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[colors.normal]
black = "#1d1f21"
red = "#cc6666"
green = "#b5bd68"
yellow = "#f0c674"
blue = "#81a2be"
magenta = "#b294bb"
cyan = "#8abeb7"
white = "#c5c8c6"

[colors.bright]
black = "#666666"
red = "#d54e53"
green = "#b9ca4a"
yellow = "#e7c547"
blue = "#7aa6da"
magenta = "#c397d8"
cyan = "#70c0b1"
white = "#eaeaea"

[selection]
save_to_clipboard = true

[cursor]
style = "Block"
unfocused_hollow = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
]
