[theme]
theme = "nord-dark"
overrides = { separator = "", separator_fg = "auto", separator_bg = "auto", idle_bg = "#000000", info_bg = "#2e3f54", good_bg = "#000000", warning_bg = "#755f2d", critical_bg = "#542a2e" }

[icons]
name = "material-nf"

[[block]]
block = "custom"
command = "redshift-brightness get"
json = true
format = " 󰃟 $text "
on_click = ""
on_click_right = ""
on_scroll_up = "redshift-brightness up"
on_scroll_down = "redshift-brightness down"
interval = 1

[[block]]
block = "sound"
format = " $icon {$volume|} "

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid|Wired} "
format_alt = " $icon {$signal_strength $ssid|Wired} $ip "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available "

[[block]]
block = "memory"
format = " $icon $mem_used_percents "
format_alt = " $icon_swap $swap_used_percents "

[[block]]
block = "load"
interval = 1
format = " $icon $1m.eng(w:4) $15m.eng(w:4) "

[[block]]
block = "cpu"
interval = 1
format = " $icon $frequency.eng(w:4) $utilization.eng(w:3) "

[[block]]
block = "battery"
format = " $icon $percentage {$time |}"
device = "BAT1"
missing_format = ""

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%V %m/%d %R') "
