services:
  APP_NAME:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ENV_FILE_PATH    # Will be replaced with absolute path
    volumes:
      - ./app:/app
      - ./workspace:/workspace
    ports:
      - "${RANDOM_PORT:-PORT}:8000"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M