apiVersion: 1

datasources:
  - name: Infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      refId: "A"
      type: "json"
      source: "url"
      url_options:
        method: "GET"
        data: ""
      parser: "backend"
      root_selector: ""
      global_queries: []