#!/usr/bin/env bash

# Output current time in the specified format
date '+%Y-%m-%d %H:%M:%S%z' | tr -d '\n' | xclip -selection clipboard

# Simulate typing from clipboard using xdotool
xdotool key shift+Insert