GOOSE_PROVIDER: openrouter
GOOSE_MODEL: anthropic/claude-3.5-sonnet

inspector:
  enabled: true
  port: 7999
  host: 0.0.0.0

extensions:
  computercontroller:
    enabled: false
    name: computercontroller
    type: builtin
  developer:
    enabled: true
    name: developer
    type: builtin
  memory:
    enabled: true
    name: memory
    type: builtin
  mcp-atlassian:
    cmd: /opt/mcp-servers/.venv/bin/python
    args:
    - -m
    - mcp_atlassian
    enabled: true
    name: mcp-atlassian
    type: stdio
    cwd: /opt/mcp-servers/mcp-atlassian
    env:
      PYTHONPATH: /opt/mcp-servers/mcp-atlassian
      # Environment variables will be loaded from .env file
      JIRA_URL: ${JIRA_URL}
      JIRA_USERNAME: ${JIRA_USERNAME}
      JIRA_API_TOKEN: ${JIRA_API_TOKEN}
  mcp-server-fetch:
    cmd: /opt/mcp-servers/.venv/bin/python
    args:
    - -m
    - mcp_server_fetch
    enabled: true
    name: mcp-server-fetch
    type: stdio
  server-memory:
    cmd: npx
    args:
    - "@modelcontextprotocol/server-memory"
    enabled: false
    name: server-memory
    type: stdio
  server-gitlab:
    cmd: npx
    args:
    - -y
    - "@modelcontextprotocol/server-gitlab"
    enabled: true
    name: server-gitlab
    type: stdio
    env:
      GITLAB_PERSONAL_ACCESS_TOKEN: ${GITLAB_PERSONAL_ACCESS_TOKEN}
      GITLAB_API_URL: ${GITLAB_API_URL}
  server-slack:
    cmd: npx
    args:
    - -y
    - "@modelcontextprotocol/server-slack"
    enabled: true
    name: server-slack
    type: stdio
    env:
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_TEAM_ID: ${SLACK_TEAM_ID}