{ config, pkgs, lib, ... }:

{
  imports = [
    ./hardware-configuration.nix  # Will be generated by nixos-generate-config
    ./display.nix                # Display and window manager configuration
    ./audio.nix                  # Audio configuration
    ./networking.nix             # Network configuration
  ];

  # Machine-specific configuration
  networking.hostName = "desktop";

  # Boot configuration
  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    # For better hardware support
    kernelPackages = pkgs.linuxPackages_latest;
    kernelModules = [ "kvm-intel" ];  # Adjust for AMD if needed
  };

  # Hardware configuration
  hardware = {
    # CPU microcode updates
    cpu.intel.updateMicrocode = true;  # Change to cpu.amd for AMD
    
    # OpenGL
    opengl = {
      enable = true;
      driSupport = true;
      driSupport32Bit = true;
    };

    # Bluetooth
    bluetooth = {
      enable = true;
      powerOnBoot = true;
    };
  };

  # Desktop environment packages
  environment.systemPackages = with pkgs; [
    # System utilities
    pciutils
    usbutils
    lm_sensors
    
    # Desktop utilities
    xclip
    xorg.xkill
    arandr
    pavucontrol
    
    # Applications
    firefox
    chromium
    alacritty
    rofi
    dunst
    feh
    
    # Media
    vlc
    mpv
    spotify
    
    # File management
    pcmanfm
    unzip
    unrar
    p7zip
    
    # System monitoring
    htop
    gotop
    neofetch
  ];

  # Font configuration
  fonts = {
    enableDefaultFonts = true;
    fonts = with pkgs; [
      (nerdfonts.override { fonts = [ "FiraCode" "DroidSansMono" ]; })
      fira-code
      fira-code-symbols
      liberation_ttf
      noto-fonts
      noto-fonts-cjk
      noto-fonts-emoji
    ];
    
    fontconfig = {
      defaultFonts = {
        monospace = [ "FiraCode Nerd Font" "DejaVu Sans Mono" ];
        sansSerif = [ "Noto Sans" "DejaVu Sans" ];
        serif = [ "Noto Serif" "DejaVu Serif" ];
      };
    };
  };

  # Service configuration
  services = {
    # Power management
    thermald.enable = true;
    tlp.enable = true;
    
    # Automounting
    udisks2.enable = true;
    gvfs.enable = true;
    
    # Printing
    printing = {
      enable = true;
      drivers = [ pkgs.gutenprint pkgs.hplip ];
    };
    
    # DBus
    dbus.enable = true;
    
    # SSH agent
    openssh.enable = true;
  };

  # Security
  security = {
    rtkit.enable = true;
    polkit.enable = true;
    
    # PAM
    pam = {
      services = {
        login.enableGnomeKeyring = true;
        swaylock = {};
      };
    };
  };

  # User-specific desktop configuration
  home-manager.users.user = { pkgs, ... }: {
    imports = [
      ../../home/profiles/desktop.nix
    ];

    # Additional user packages
    home.packages = with pkgs; [
      # Communication
      discord
      slack
      zoom-us
      
      # Development
      insomnia
      postman
      
      # Graphics
      gimp
      inkscape
      
      # Office
      libreoffice
      
      # Utilities
      flameshot
      keepassxc
    ];
  };

  # System state version
  system.stateVersion = "23.11";
}
