version: '3'
services:
  grafana:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grafana
    network_mode: "host"
    # When using host network mode, container ports are published directly to the host
    # No need for port mapping
    volumes:
      - /home/user/git/github/monorepo/tools/grafana/data:/var/lib/grafana
      - /home/user/git/github/monorepo/tools/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - /home/user/git/github/monorepo/tools/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=http://localhost:3100
      - GF_SERVER_HTTP_PORT=3100
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_PLUGINS_PREINSTALL=yesoreyeram-infinity-datasource
    restart: unless-stopped